CC=x86_64-w64-mingw32-gcc
CFLAGS=-I /usr/include/SDL2
DEPS= chip8.h debug.h
TARGET= chip8.exe

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

makechip8disassembler: src/debug.o src/chip8.o 
		@mkdir -p bin
		$(CC) -Wall -std=c99 -o ./bin/$(TARGET) ./src/debug.c ./src/chip8.c `sdl2-config --cflags --libs`

clean:
	rm ./bin/$(TARGET)
	rm ./src/chip8.o
	rm ./src/debug.o
