CC=x86_64-w64-mingw32-gcc
CFLAGS=-I /usr/include/SDL2
DEPS= chip8.h debug.h
TARGET= chip8.exe

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

makechip8disassembler: src/debug.o src/chip8.o src/system.o
		@mkdir -p bin/win
		$(CC) -Wall -std=c99 -o ./bin/win/$(TARGET) src/system.c ./src/debug.c ./src/chip8.c `sdl2-config --cflags --libs`

clean:
	rm ./bin/win/$(TARGET)
	rm ./src/chip8.o
	rm ./src/debug.o
	rm ./src/system.o
	rm -rf ./release/